### ISSUE TITLE
Attribute 'title' and attribute 'name' not allowed

### ISSUE THREAD

**Issue by corymosiman12** [pnnl/assetscore-schematron-docs#1]
Hey @markborkum, just came across this when trying to run schematron validation in OxygenXML.  If I delete the name and title attributes, then the validation works, however, it won't run a validation unless I delete these.  Is this an OxygenXML issue?

![Screen Shot 2019-11-06 at 3 08 53 PM](https://user-images.githubusercontent.com/28991233/68342334-96565480-00a7-11ea-9473-05d6bb90f90e.png)

![Screen Shot 2019-11-06 at 3 12 10 PM](https://user-images.githubusercontent.com/28991233/68342448-da495980-00a7-11ea-8276-d84ffac7fe7f.png)

**Comment by markborkum** [comment]
@corymosiman12 Presumably. My guess is that OxygenXML is attempting to validate the XML content of the Schematron document, but cannot find the XSD file for the "sch" XML namespace. To make the Schematron document compatible with OxygenXML, try adding the following attributes to the `<sch:schema>` element:
```
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="path/to/schematron.xsd"
```
where `path/to/schematron.xsd` is the relative path.

**Comment by corymosiman12** [comment]
You're saying to add those attributes into the [Schematron XML file](https://raw.githubusercontent.com/BuildingSync/assetscore-schematron-docs/master/docs/Audit_Template/New_York_City_Energy_Efficiency_Report.xml)?  Where would I get a `schematron.xsd` file?  I thought that was all embedded as part of the Schematron standard?

**Comment by markborkum** [comment]
@corymosiman12 Correct. On the [Schematron website](http://schematron.com/front-page/the-schematron-skeleton-implementation/), on the "Implementation" page, in the "Resources" section, there is a link to the [RELAX NG schema](http://schematron.com/wp-content/uploads/2018/02/schematron.rnc_.txt) for ISO Schematron 2016. You can use a ["Conversion Tool"](https://relaxng.org/#conversion) to convert from RELAX NG to XSD format, e.g., [Trang](https://github.com/relaxng/jing-trang).

**Comment by corymosiman12** [comment]
ok so I found this [iso-schematron.xsd](https://raw.githubusercontent.com/esacinc/sdcct/master/sdcct-core/src/main/resources/META-INF/sdcct/schema/schematron/iso-schematron.xsd).

It's saved here: `/Users/cmosiman/Downloads/iso-schematron.xsd`

I added title to the schema element:
![Screen Shot 2019-11-06 at 5 03 48 PM](https://user-images.githubusercontent.com/28991233/68348627-aaa24d80-00b7-11ea-9c41-a4fe6b674926.png)

I also added name to the pattern element:
![Screen Shot 2019-11-06 at 5 08 12 PM](https://user-images.githubusercontent.com/28991233/68348754-0b318a80-00b8-11ea-9f66-0cb015aea9e3.png)

I added this to my New_York...xml file
`xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://purl.oclc.org/dsdl/schematron /Users/cmosiman/Downloads/iso-schematron.xsd"` (they are also both in the downloads folder, so I tried: `./iso-schematron.xsd` and `iso-schematron.xsd` as well.  Am still getting the same errors...doing anything obviously wrong?

**Comment by markborkum** [comment]
@corymosiman12 Thanks for your efforts. I've updated the Schematron document to conform to that XSD file.

**Comment by corymosiman12** [comment]
@markborkum 
other errors went away...but...getting this with the new file...
![image](https://user-images.githubusercontent.com/28991233/68416895-9d866c80-0152-11ea-905c-b1ae0c545dfe.png)

**Comment by markborkum** [comment]
@corymosiman12 We're getting close. The error message is correct. 3c602a8d1817aff13ac71dac7852c27bcf92f470 should resolve this issue.

**Comment by corymosiman12** [comment]
@markborkum woohoo! thanks, working as expected!
